$ANSIBLE_VAULT;1.1;AES256
63326438396135346438626239323235613435633232393332363862613131623035353065636535
3464663632336266656363663138303162613461316639340a303934636530363031653961363961
36323438666634393535646465646233366236303863373962313338353130393339616365383063
3032353265376363310a343438323039626266633233366336643763633533313132383062313131
65313335366638323139303066346664393539333334313261346266646433363334646665353539
30666433386465306464353763623233316434636230616339303862616632336361306139623536
33363530666132396631396139303734336431666339613738656532386531626335336262646664
34326164633433623565623033386234383132636235393066383434363337663731306336653762
61653764356237633631313531333064383664386461636330633339373065623632333636396261
62616463333939353938346131653930346266396430323939366366393965393435303462303631
39393937326432653365656330346237373663356136323037353835333361383137343132386462
63306161396638376139343261666364316337386465626531373962343334303837636633613135
39613331386366636631613663306535313734653738393735336333346464353965653262333466
30666336376332633533653463393766666631306431623437323464393561666530653035346639
35343263333036623139356136366166616130636431616238316461363666343564316232326337
64333633373736303534383561386238393366353465303163666233366362303336326366623963
63386238626537663862346433626262303335303130353662663164613531333363656366376434
66363036666465363537663034343566303161623633616165393361636137633565383836623561
37626164313133373562643838376565663936626235313163396638633066626133383633613161
35666232346337313131323238616632313532336134393630633062336436393336326436616363
63346234373037373062383337613562616665353039633962616363386464613338636238333264
35656331646562636636643739333037346565653337646237323464336262626534326162306464
306362383336336266666662373866356635
